/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;

/**
 *
 * @author 232.975989
 */
public class UrnaEletronica extends javax.swing.JFrame {

    /**
     * Creates new form view
     */
    public UrnaEletronica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        telaBackground = new javax.swing.JPanel();
        telaTreinamento = new javax.swing.JPanel();
        lblCampo1 = new javax.swing.JLabel();
        lblCampo2 = new javax.swing.JLabel();
        lblCampo3 = new javax.swing.JLabel();
        lblCampo4 = new javax.swing.JLabel();
        lblVereadorTxt = new javax.swing.JLabel();
        lblTreinamentoTxt = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblPartido = new javax.swing.JLabel();
        lblNomeCandidato = new javax.swing.JLabel();
        lblNomePartido = new javax.swing.JLabel();
        lblPersonagem = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblFimTxt = new javax.swing.JLabel();
        lblVotouTxt = new javax.swing.JLabel();
        lblAviso1 = new javax.swing.JLabel();
        lblCampo5 = new javax.swing.JLabel();
        lblAviso2 = new javax.swing.JLabel();
        telaTeclado = new javax.swing.JPanel();
        btnNum1 = new javax.swing.JButton();
        btnNum2 = new javax.swing.JButton();
        btnNum3 = new javax.swing.JButton();
        btnNum4 = new javax.swing.JButton();
        btnNum5 = new javax.swing.JButton();
        btnNum6 = new javax.swing.JButton();
        btnNum7 = new javax.swing.JButton();
        btnNum8 = new javax.swing.JButton();
        btnNum9 = new javax.swing.JButton();
        btnNum0 = new javax.swing.JButton();
        btnBranco = new javax.swing.JButton();
        btnCorrige = new javax.swing.JButton();
        btnConfirma = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList<>();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList5 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("4");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        telaBackground.setBackground(new java.awt.Color(204, 204, 204));

        telaTreinamento.setBackground(new java.awt.Color(255, 255, 255));

        lblCampo1.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        lblCampo2.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        lblCampo3.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        lblCampo4.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        lblVereadorTxt.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        lblVereadorTxt.setText("Vereador");

        lblTreinamentoTxt.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        lblTreinamentoTxt.setForeground(new java.awt.Color(102, 102, 102));
        lblTreinamentoTxt.setText("TREINAMENTO");

        lblNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNome.setText("Nome:");

        lblPartido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPartido.setText("Partido:");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        lblFimTxt.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        lblFimTxt.setText("FIM");

        lblVotouTxt.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        lblVotouTxt.setForeground(new java.awt.Color(102, 102, 102));
        lblVotouTxt.setText("VOTOU");

        lblAviso1.setText("Aperte a Tecla: CONFIRMA para CONFIRMAR este voto");

        lblCampo5.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        lblAviso2.setText("CORRIGE para REINICIAR este voto");

        javax.swing.GroupLayout telaTreinamentoLayout = new javax.swing.GroupLayout(telaTreinamento);
        telaTreinamento.setLayout(telaTreinamentoLayout);
        telaTreinamentoLayout.setHorizontalGroup(
            telaTreinamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaTreinamentoLayout.createSequentialGroup()
                .addGroup(telaTreinamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(telaTreinamentoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(telaTreinamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(telaTreinamentoLayout.createSequentialGroup()
                                .addComponent(lblPartido)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblNomePartido, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblVotouTxt))
                            .addGroup(telaTreinamentoLayout.createSequentialGroup()
                                .addComponent(lblNome)
                                .addGap(18, 18, 18)
                                .addComponent(lblNomeCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(telaTreinamentoLayout.createSequentialGroup()
                        .addGroup(telaTreinamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(telaTreinamentoLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(telaTreinamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(telaTreinamentoLayout.createSequentialGroup()
                                        .addComponent(lblCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblCampo2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblCampo3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblCampo4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblCampo5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(89, 89, 89)
                                        .addComponent(lblFimTxt))
                                    .addComponent(lblVereadorTxt))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, telaTreinamentoLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblTreinamentoTxt)
                                .addGap(160, 160, 160)))
                        .addComponent(lblPersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(telaTreinamentoLayout.createSequentialGroup()
                .addGroup(telaTreinamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(telaTreinamentoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblAviso1))
                    .addGroup(telaTreinamentoLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(lblAviso2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        telaTreinamentoLayout.setVerticalGroup(
            telaTreinamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaTreinamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(telaTreinamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(telaTreinamentoLayout.createSequentialGroup()
                        .addComponent(lblTreinamentoTxt)
                        .addGap(40, 40, 40)
                        .addComponent(lblVereadorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(telaTreinamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCampo4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCampo3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCampo2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCampo1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFimTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCampo5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblPersonagem, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(telaTreinamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(lblNomeCandidato, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(telaTreinamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(telaTreinamentoLayout.createSequentialGroup()
                        .addGroup(telaTreinamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPartido)
                            .addComponent(lblNomePartido, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblVotouTxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAviso1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAviso2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout telaBackgroundLayout = new javax.swing.GroupLayout(telaBackground);
        telaBackground.setLayout(telaBackgroundLayout);
        telaBackgroundLayout.setHorizontalGroup(
            telaBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaBackgroundLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(telaTreinamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        telaBackgroundLayout.setVerticalGroup(
            telaBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaBackgroundLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(telaTreinamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        telaTeclado.setBackground(new java.awt.Color(51, 51, 51));

        btnNum1.setBackground(new java.awt.Color(0, 0, 0));
        btnNum1.setFont(new java.awt.Font("Swis721 Lt BT", 0, 12)); // NOI18N
        btnNum1.setForeground(new java.awt.Color(255, 255, 255));
        btnNum1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/n1.jpg"))); // NOI18N
        btnNum1.setText("1");
        btnNum1.setBorderPainted(false);

        btnNum2.setBackground(new java.awt.Color(0, 0, 0));
        btnNum2.setFont(new java.awt.Font("Swis721 Lt BT", 0, 12)); // NOI18N
        btnNum2.setForeground(new java.awt.Color(255, 255, 255));
        btnNum2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/n2.jpg"))); // NOI18N
        btnNum2.setText("2");
        btnNum2.setBorderPainted(false);
        btnNum2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum2ActionPerformed(evt);
            }
        });

        btnNum3.setBackground(new java.awt.Color(0, 0, 0));
        btnNum3.setFont(new java.awt.Font("Swis721 Lt BT", 0, 12)); // NOI18N
        btnNum3.setForeground(new java.awt.Color(255, 255, 255));
        btnNum3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/n3.jpg"))); // NOI18N
        btnNum3.setText("3");
        btnNum3.setBorderPainted(false);
        btnNum3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNum3ActionPerformed(evt);
            }
        });

        btnNum4.setBackground(new java.awt.Color(0, 0, 0));
        btnNum4.setFont(new java.awt.Font("Swis721 Lt BT", 0, 12)); // NOI18N
        btnNum4.setForeground(new java.awt.Color(255, 255, 255));
        btnNum4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/n4.jpg"))); // NOI18N
        btnNum4.setText("1");
        btnNum4.setBorderPainted(false);

        btnNum5.setBackground(new java.awt.Color(0, 0, 0));
        btnNum5.setFont(new java.awt.Font("Swis721 Lt BT", 0, 12)); // NOI18N
        btnNum5.setForeground(new java.awt.Color(255, 255, 255));
        btnNum5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/n5.jpg"))); // NOI18N
        btnNum5.setText("1");
        btnNum5.setBorderPainted(false);

        btnNum6.setBackground(new java.awt.Color(0, 0, 0));
        btnNum6.setFont(new java.awt.Font("Swis721 Lt BT", 0, 12)); // NOI18N
        btnNum6.setForeground(new java.awt.Color(255, 255, 255));
        btnNum6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/n6.jpg"))); // NOI18N
        btnNum6.setText("1");
        btnNum6.setBorderPainted(false);

        btnNum7.setBackground(new java.awt.Color(0, 0, 0));
        btnNum7.setFont(new java.awt.Font("Swis721 Lt BT", 0, 12)); // NOI18N
        btnNum7.setForeground(new java.awt.Color(255, 255, 255));
        btnNum7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/n7.jpg"))); // NOI18N
        btnNum7.setText("1");
        btnNum7.setBorderPainted(false);

        btnNum8.setBackground(new java.awt.Color(0, 0, 0));
        btnNum8.setFont(new java.awt.Font("Swis721 Lt BT", 0, 12)); // NOI18N
        btnNum8.setForeground(new java.awt.Color(255, 255, 255));
        btnNum8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/n8.jpg"))); // NOI18N
        btnNum8.setText("1");
        btnNum8.setBorderPainted(false);

        btnNum9.setBackground(new java.awt.Color(0, 0, 0));
        btnNum9.setFont(new java.awt.Font("Swis721 Lt BT", 0, 12)); // NOI18N
        btnNum9.setForeground(new java.awt.Color(255, 255, 255));
        btnNum9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/n9.jpg"))); // NOI18N
        btnNum9.setText("1");
        btnNum9.setBorderPainted(false);

        btnNum0.setBackground(new java.awt.Color(0, 0, 0));
        btnNum0.setFont(new java.awt.Font("Swis721 Lt BT", 0, 12)); // NOI18N
        btnNum0.setForeground(new java.awt.Color(255, 255, 255));
        btnNum0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/n0.jpg"))); // NOI18N
        btnNum0.setText("1");
        btnNum0.setBorderPainted(false);

        btnBranco.setBackground(new java.awt.Color(0, 0, 0));
        btnBranco.setFont(new java.awt.Font("Swis721 Lt BT", 0, 12)); // NOI18N
        btnBranco.setForeground(new java.awt.Color(255, 255, 255));
        btnBranco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/branco.jpg"))); // NOI18N
        btnBranco.setText("1");
        btnBranco.setBorderPainted(false);

        btnCorrige.setBackground(new java.awt.Color(0, 0, 0));
        btnCorrige.setFont(new java.awt.Font("Swis721 Lt BT", 0, 12)); // NOI18N
        btnCorrige.setForeground(new java.awt.Color(255, 255, 255));
        btnCorrige.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/corrige.jpg"))); // NOI18N
        btnCorrige.setText("1");
        btnCorrige.setBorderPainted(false);

        btnConfirma.setBackground(new java.awt.Color(0, 0, 0));
        btnConfirma.setFont(new java.awt.Font("Swis721 Lt BT", 0, 12)); // NOI18N
        btnConfirma.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/confirma.jpg"))); // NOI18N
        btnConfirma.setText("1");
        btnConfirma.setBorderPainted(false);

        javax.swing.GroupLayout telaTecladoLayout = new javax.swing.GroupLayout(telaTeclado);
        telaTeclado.setLayout(telaTecladoLayout);
        telaTecladoLayout.setHorizontalGroup(
            telaTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaTecladoLayout.createSequentialGroup()
                .addGroup(telaTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(telaTecladoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBranco, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, telaTecladoLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(telaTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnNum7, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNum4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(telaTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(telaTecladoLayout.createSequentialGroup()
                        .addComponent(btnCorrige, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnConfirma, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13))
                    .addGroup(telaTecladoLayout.createSequentialGroup()
                        .addGroup(telaTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNum0, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(telaTecladoLayout.createSequentialGroup()
                                .addGroup(telaTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnNum5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnNum8, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                .addGap(25, 25, 25)
                                .addGroup(telaTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnNum9, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnNum3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnNum6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(23, 23, 23))))
        );
        telaTecladoLayout.setVerticalGroup(
            telaTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(telaTecladoLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(telaTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(telaTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(btnNum3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(telaTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNum4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNum5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNum6, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(telaTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNum7, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNum8, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNum9, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNum0, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(telaTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBranco, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCorrige, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfirma, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        jLabel18.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Partido RITMOS MSC.");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "GOLFE - 91001", "BEISEBOL - 91002", "GINÁSTICA A. - 91003" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel19.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Partido ESPORTES");

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "ROCK - 92001", "SERTANEJO - 92002", "MPB - 92003" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        jLabel20.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Partido PROFISSÕES");

        jList3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "ASTRONAUTA - 93001", "PINTOR - 93002", "ENFERMEIRA - 93003" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList3);

        jLabel21.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Partido FESTAS P.");

        jList4.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "PÁSCOA - 94001", "OKTOBERFEST - 94002", "REVEILLON - 94003" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jList4);

        jLabel22.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Partido FOLCLORE");

        jList5.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "CURUPIRA - 95001", "CABRA CABRIOLA - 95002", "CUCA - 95003" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(jList5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel19))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel21)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\232.975989\\Pictures\\logo.PNG")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(telaBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(telaTeclado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(telaBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(telaTeclado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(99, 99, 99))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNum2ActionPerformed

    private void btnNum3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNum3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNum3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UrnaEletronica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UrnaEletronica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UrnaEletronica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UrnaEletronica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UrnaEletronica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBranco;
    private javax.swing.JButton btnConfirma;
    private javax.swing.JButton btnCorrige;
    private javax.swing.JButton btnNum0;
    private javax.swing.JButton btnNum1;
    private javax.swing.JButton btnNum2;
    private javax.swing.JButton btnNum3;
    private javax.swing.JButton btnNum4;
    private javax.swing.JButton btnNum5;
    private javax.swing.JButton btnNum6;
    private javax.swing.JButton btnNum7;
    private javax.swing.JButton btnNum8;
    private javax.swing.JButton btnNum9;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jList3;
    private javax.swing.JList<String> jList4;
    private javax.swing.JList<String> jList5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAviso1;
    private javax.swing.JLabel lblAviso2;
    private javax.swing.JLabel lblCampo1;
    private javax.swing.JLabel lblCampo2;
    private javax.swing.JLabel lblCampo3;
    private javax.swing.JLabel lblCampo4;
    private javax.swing.JLabel lblCampo5;
    private javax.swing.JLabel lblFimTxt;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNomeCandidato;
    private javax.swing.JLabel lblNomePartido;
    private javax.swing.JLabel lblPartido;
    private javax.swing.JLabel lblPersonagem;
    private javax.swing.JLabel lblTreinamentoTxt;
    private javax.swing.JLabel lblVereadorTxt;
    private javax.swing.JLabel lblVotouTxt;
    private javax.swing.JPanel telaBackground;
    private javax.swing.JPanel telaTeclado;
    private javax.swing.JPanel telaTreinamento;
    // End of variables declaration//GEN-END:variables
}
